language: node_js
node_js:
    - 10
branches:
    only:
        - master
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
install:
    - yarn
script:
    - yarn test
after_success:
    - yarn run coveralls
